import { Fragment, useState } from "react";
import { Card, CardContent, Typography, IconButton } from "@mui/material";
import Avatar from "@mui/material/Avatar";
import AspectRatioIcon from "@mui/icons-material/AspectRatio";
import ListAltOutlinedIcon from "@mui/icons-material/ListAltOutlined";
import Table from "@mui/material/Table";
import TableBody from "@mui/material/TableBody";
import TableCell from "@mui/material/TableCell";
import TableContainer from "@mui/material/TableContainer";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import Paper from "@mui/material/Paper";

function LessonList(props) {
  const [expand, setExpand] = useState(false);
  const [singleContent, setSingleContent] = useState();
  console.log(singleContent);

  function viewLesson(lessonData) {
    console.log(lessonData);
    setSingleContent(
      <Card key={lessonData.timestamp}>
        <CardContent sx={{ paddingBottom: 1 }}>
          <Typography variant="h5">{lessonData.lessonTitle}</Typography>
          <div
            style={{
              display: "grid",
              gridAutoFlow: "column",
              justifyContent: "start",
              alignItems: "center",
              gap: 10,
              paddingTop: 3,
            }}
          >
            <Avatar
              sx={{ width: 24, height: 24 }}
              src={lessonData.user && lessonData.user.photoURL}
            ></Avatar>
            <Typography variant="subtitle1">
              Generated by{" "}
              {props.lessons[0].displayName
                ? props.lessons[0].displayName
                : "Anonymous"}
            </Typography>
          </div>
          <IconButton onClick={() => setExpand(false)}>
            <ListAltOutlinedIcon color="primary" fontSize="medium" />
          </IconButton>
        </CardContent>

        <CardContent>
          <Typography
            sx={{ whiteSpace: "pre-line", marginTop: -3 }}
            variant="body1"
          >
            {lessonData.generatedLesson}
          </Typography>
        </CardContent>
      </Card>
    );
    setExpand(true);
  }

  return expand ? (
    <Fragment>
      <h1>{singleContent}</h1>
    </Fragment>
  ) : (
    <Fragment>
      <TableContainer component={Paper}>
        <Table sx={{ minWidth: 650 }} aria-label="simple table">
          <TableHead>
            <TableRow>
              <TableCell align="center">Actions</TableCell>
              <TableCell>Lesson</TableCell>
              <TableCell align="right">Subject</TableCell>
              <TableCell align="right">Grade</TableCell>
              <TableCell align="right">Date</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {props.lessons[0].generatedLessons.map((row) => (
              <TableRow
                key={row.name}
                sx={{ "&:last-child td, &:last-child th": { border: 0 } }}
              >
                <TableCell
                  align="right"
                  sx={{ display: "grid", gridTemplateColumns: "1fr 1fr" }}
                >
                  <IconButton
                    variant="outlined"
                    onClick={() => viewLesson(row)}
                  >
                    <AspectRatioIcon color="primary" fontSize="small" />
                  </IconButton>
                </TableCell>
                <TableCell component="th" scope="row">
                  {row.lessonTitle}
                </TableCell>
                <TableCell align="right">{row.subject}</TableCell>
                <TableCell align="right">{row.grade}</TableCell>
                <TableCell align="right">-</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </TableContainer>
    </Fragment>
  );
}

export default LessonList;
